[project]
name = "cassapeak-orchestrator"
version = "0.1.0"
description = "Service for orchestation of all the CassaPeak services"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-on-whales>=0.77.0",
    "fastapi[standard]",
]
